main: cn.eggpixel.EmeraldTools
name: EmeraldTools
version: 1.0.0
author: EmeraldsEgg
api-version: 1.13

commands:
  kills:
    usage: '§cUsage: /kills'
    description: Kill yourself.
    permission: emeraldtools.kills
    permission-message: '§cYou do not have permission to do this!'
  kill:
    usage: '§cUsage: /kill [Player] or /kill [Entity UUID]'
    description: Kill a player or a entity.
    permission: emeraldtools.kill
    permission-message: '§cYou do not have permission to do this!'
  fly:
    usage: '§cUsage: /fly or /fly [Player]'
    description: Make a player can fly.
    permission: emeraldtools.fly
    permission-message: '§cYou do not have permission to do this!'
  vanish:
    usage: '§cUsage: /v or /v [Player]'
    description: Vanish a player.
    permission: emeraldtools.vanish
    permission-message: '§cYou do not have permission to do this!'
    aliases: [v]
  heal:
    usage: '§cUsage: /heal or /heal [Player]'
    description: Heal a player.
    permission: emeraldtools.heal
    permission-message: '§cYou do not have permission to do this!'
  emeraldtools:
    usage: '§cUsage: /emeraldtools reload'
    description: Reload the plugin.
    permission: emeraldtools.admin
    permission-message: '§cYou do not have permission to do this!'
  burn:
    usage: '§cUsage: /burn <Player> [Tick]'
    description: Make a player burning
    permission: emeraldtools.burn
    permission-message: '§cYou do not have permission to do this!'
permissions:
  emeraldtools.admin:
    description: 'Plugin Management Permission'
    default: op
    children:
      emeraldtools.kills: true
      emeraldtools.kill: true
      emeraldtools.fly: true
      emeraldtools.vanish: true
      emeraldtools.heal: true
      emeraldtools.burn: true
  emeraldtools.vanish:
    default: op
    children:
      emeraldtools.vanish.see: true
  emeraldtools.kills:
    default: true
  emeraldtools.kill:
    default: op
  emeraldtools.fly:
    default: op
  emeraldtools.vanish.see:
    default: op
  emeraldtools.heal:
    default: op
  emeraldtools.burn:
    default: op